name: ci

on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ "3.13" ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -r ./requirements.txt
    - name: flake8 linting
      run: python -m flake8 ./
    - name: black formatting check
      run: python -m black --check ./
    - name: isort formatting check
      run: python -m isort --check ./
    - name: mypy type checking
      run: python -m mypy ./
